import manifest from '@/data/imageManifest.json';

/**
 * Maps a master image path — the URL shape stored in product/hamper data and
 * returned by the API, e.g. `/images/products/kids_bag/Beach.png` — onto the
 * responsive WebP variants generated by `scripts/convert-images.mjs`.
 *
 * The masters themselves live in `assets-src/` and are never deployed, so any
 * path present in the manifest MUST be rewritten before it reaches the DOM.
 * Paths that aren't in the manifest (absolute URLs, an OAuth avatar) pass
 * through untouched.
 */

interface ManifestEntry {
  /** Variant path without the `-<width>.webp` suffix. */
  b: string;
  /** Widths available, ascending. */
  w: number[];
}

const variants: Record<string, ManifestEntry | undefined> = manifest;

/** Widest variant we hand to a browser that ignores `srcSet`. */
const FALLBACK_WIDTH = 800;

export interface ImageSources {
  src: string;
  srcSet?: string;
}

const variantUrl = (entry: ManifestEntry, width: number) => `${entry.b}-${width}.webp`;

export function imageSources(src: string | undefined | null): ImageSources {
  if (!src) return { src: '' };

  const entry = variants[src];
  if (!entry) return { src };

  const fallback =
    [...entry.w].reverse().find((w) => w <= FALLBACK_WIDTH) ?? entry.w[entry.w.length - 1];

  return {
    src: variantUrl(entry, fallback),
    srcSet: entry.w.map((w) => `${variantUrl(entry, w)} ${w}w`).join(', '),
  };
}

/**
 * Single-width variant, for slots whose display size is fixed and tiny
 * (colour swatches, cart thumbnails) where a full `srcSet` buys nothing.
 */
export function imageAtWidth(src: string | undefined | null, width: number): string {
  if (!src) return '';

  const entry = variants[src];
  if (!entry) return src;

  return variantUrl(entry, entry.w.find((w) => w >= width) ?? entry.w[entry.w.length - 1]);
}
